# GitHub Action for generating a contribution snake animation

name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generates the snake animation SVG
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}
          
          # A list of files to generate
          # The snake SVG will be available at dist/snake.svg
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-3d.svg?palette=github-dark&color_snake=orange

      # Pushes the generated files to the 'output' branch
      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
